### ISSUE TITLE
Not working with node red 0.20.0 beta

### ISSUE THREAD

**Issue by vd062** [krisdaniels/node-red-contrib#13]
I updated to beta for some reasons and this node stared showing errors : " Cannot find module C:\Users\Vishal\AppData\Roaming\npm\node_modules\node-red/red/red' (line:17)"

I posted issue on beta release news and got answer that the code is poorly written.

**Comment by elmicha** [comment]
The same with the final 0.20.0 on Raspberry Pi:
```
12 Mar 19:13:49 - [warn] [node-red-contrib-postgres/PostgreSql] Error: Cannot find module '/usr/lib/node_modules/node-red/red/red' (line:17)
```
